local html = {}

html["a"] = "a[href]"
html["a:blank"] = "a[href='http://${0}' target='_blank' rel='noopener noreferrer']"
html["a:link"] = "a[href='http://${0}']"
html["a:mail"] = "a[href='mailto:${0}']"
html["a:tel"] = "a[href='tel:+${0}']"
html["abbr"] = "abbr[title]"
html["acr|acronym"] = "acronym[title]"
html["base"] = "base[href]/"
html["basefont"] = "basefont/"
html["br"] = "br/"
html["frame"] = "frame/"
html["hr"] = "hr/"
html["bdo"] = "bdo[dir]"
html["bdo:r"] = "bdo[dir=rtl]"
html["bdo:l"] = "bdo[dir=ltr]"
html["col"] = "col/"
html["link"] = "link[rel=stylesheet href]/"
html["link:css"] = "link[href='${1:style}.css']"
html["link:print"] = "link[href='${1:print}.css' media=print]"
html["link:favicon"] = "link[rel='shortcut icon' type=image/x-icon href='${1:favicon.ico}']"
html["link:mf|link:manifest"] = "link[rel='manifest' href='${1:manifest.json}']"
html["link:touch"] = "link[rel=apple-touch-icon href='${1:favicon.png}']"
html["link:rss"] = "link[rel=alternate type=application/rss+xml title=RSS href='${1:rss.xml}']"
html["link:atom"] = "link[rel=alternate type=application/atom+xml title=Atom href='${1:atom.xml}']"
html["link:im|link:import"] = "link[rel=import href='${1:component}.html']"
html["meta"] = "meta/"
html["meta:utf"] = "meta[http-equiv=Content-Type content='text/html;charset=UTF-8']"
html["meta:vp"] = "meta[name=viewport content='width=${1:device-width}, initial-scale=${2:1.0}']"
html["meta:compat"] = "meta[http-equiv=X-UA-Compatible content='${1:IE=7}']"
html["meta:edge"] = "meta:compat[content='${1:ie=edge}']"
html["meta:redirect"] = "meta[http-equiv=refresh content='0; url=${1:http://example.com}']"
html["meta:kw"] = "meta[name=keywords content]"
html["meta:desc"] = "meta[name=description content]"
html["style"] = "style"
html["script"] = "script"
html["script:src"] = "script[src]"
html["img"] = "img[src alt]/"
html["img:s|img:srcset"] = "img[srcset src alt]"
html["img:z|img:sizes"] = "img[sizes srcset src alt]"
html["picture"] = "picture"
html["src|source"] = "source/"
html["src:sc|source:src"] = "source[src type]"
html["src:s|source:srcset"] = "source[srcset]"
html["src:t|source:type"] = "source[srcset type='${1:image/}']"
html["src:z|source:sizes"] = "source[sizes srcset]"
html["src:m|source:media"] = "source[media='(${1:min-width: })' srcset]"
html["src:mt|source:media:type"] = "source:media[type='${2:image/}']"
html["src:mz|source:media:sizes"] = "source:media[sizes srcset]"
html["src:zt|source:sizes:type"] = "source[sizes srcset type='${1:image/}']"
html["iframe"] = "iframe[src frameborder=0]"
html["embed"] = "embed[src type]/"
html["object"] = "object[data type]"
html["param"] = "param[name value]/"
html["map"] = "map[name]"
html["area"] = "area[shape coords href alt]/"
html["area:d"] = "area[shape=default]"
html["area:c"] = "area[shape=circle]"
html["area:r"] = "area[shape=rect]"
html["area:p"] = "area[shape=poly]"
html["form"] = "form[action]"
html["form:get"] = "form[method=get]"
html["form:post"] = "form[method=post]"
html["label"] = "label[for]"
html["input"] = "input[type=${1:text}]/"
html["inp"] = "input[name=${1} id=${1}]"
html["input:h|input:hidden"] = "input[type=hidden name]"
html["input:t|input:text"] = "inp[type=text]"
html["input:search"] = "inp[type=search]"
html["input:email"] = "inp[type=email]"
html["input:url"] = "inp[type=url]"
html["input:p|input:password"] = "inp[type=password]"
html["input:datetime"] = "inp[type=datetime]"
html["input:date"] = "inp[type=date]"
html["input:datetime-local"] = "inp[type=datetime-local]"
html["input:month"] = "inp[type=month]"
html["input:week"] = "inp[type=week]"
html["input:time"] = "inp[type=time]"
html["input:tel"] = "inp[type=tel]"
html["input:number"] = "inp[type=number]"
html["input:color"] = "inp[type=color]"
html["input:c|input:checkbox"] = "inp[type=checkbox]"
html["input:r|input:radio"] = "inp[type=radio]"
html["input:range"] = "inp[type=range]"
html["input:f|input:file"] = "inp[type=file]"
html["input:s|input:submit"] = "input[type=submit value]"
html["input:i|input:image"] = "input[type=image src alt]"
html["input:b|input:btn|input:button"] = "input[type=button value]"
html["input:reset"] = "input:button[type=reset]"
html["isindex"] = "isindex/"
html["select"] = "select[name=${1} id=${1}]"
html["select:d|select:disabled"] = "select[disabled.]"
html["opt|option"] = "option[value]"
html["textarea"] = "textarea[name=${1} id=${1} cols=${2:30} rows=${3:10}]"
html["marquee"] = "marquee[behavior direction]"
html["menu:c|menu:context"] = "menu[type=context]"
html["menu:t|menu:toolbar"] = "menu[type=toolbar]"
html["video"] = "video[src]"
html["audio"] = "audio[src]"
html["html:xml"] = "html[xmlns=http://www.w3.org/1999/xhtml]"
html["keygen"] = "keygen/"
html["command"] = "command/"
html["btn:s|button:s|button:submit"] = "button[type=submit]"
html["btn:r|button:r|button:reset"] = "button[type=reset]"
html["btn:d|button:d|button:disabled"] = "button[disabled.]"
html["fst:d|fset:d|fieldset:d|fieldset:disabled"] = "fieldset[disabled.]"
html["bq"] = "blockquote"
html["fig"] = "figure"
html["figc"] = "figcaption"
html["pic"] = "picture"
html["ifr"] = "iframe"
html["emb"] = "embed"
html["obj"] = "object"
html["cap"] = "caption"
html["colg"] = "colgroup"
html["fst"] = "fieldset"
html["btn"] = "button"
html["optg"] = "optgroup"
html["tarea"] = "textarea"
html["leg"] = "legend"
html["sect"] = "section"
html["art"] = "article"
html["hdr"] = "header"
html["ftr"] = "footer"
html["adr"] = "address"
html["dlg"] = "dialog"
html["str"] = "strong"
html["prog"] = "progress"
html["mn"] = "main"
html["tem"] = "template"
html["fset"] = "fieldset"
html["datag"] = "datagrid"
html["datal"] = "datalist"
html["kg"] = "keygen"
html["out"] = "output"
html["det"] = "details"
html["sum"] = "summary"
html["cmd"] = "command"
html["ri:d|ri:dpr"] = "img:s"
html["ri:v|ri:viewport"] = "img:z"
html["ri:a|ri:art"] = "pic>src:m+img"
html["ri:t|ri:type"] = "pic>src:t+img"
html["!!!"] = "{<!DOCTYPE html>}"
html["doc"] = "html[lang=${lang}]>(head>meta[charset=${charset}]+meta[http-equiv='X-UA-Compatible'][content='IE=edge']+meta:vp+title{${1:Document}})+body"
html["!|html:5"] = "!!!+doc"
html["c"] = "{<!-- ${0} -->}"
html["cc:ie"] = "{<!--[if IE]>${0}<![endif]-->}"
html["cc:noie"] = "{<!--[if !IE]><!-->${0}<!--<![endif]-->}"

return html
